<?php
/**
 * Created by PhpStorm.
 * User: ярик
 * Date: 25.07.2016
 * Time: 1:26
 */

namespace common\ext\models;


use yii\db\Migration;

class SimplexMigration extends Migration
{
    const DEFAULT_MYSQL_TABLE_OPTIONS = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=MyISAM';

    public function createTable($table, $columns, $options = null)
    {
        $options = $options ?$options: self::DEFAULT_MYSQL_TABLE_OPTIONS;
        parent::createTable($table, $columns, $options); // TODO: Change the autogenerated stub
    }


}